name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
