name: Release
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing bun
        uses: oven-sh/setup-bun@v2
      - name: Installing dependencies with bun
        run: bun install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: master
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/release-notes-generator
            @semantic-release/github
